# Generated by Django 4.2.28 on 2026-02-10 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('healthcare', 'Healthcare'), ('education', 'Education'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('technology', 'Technology'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], default='other', max_length=50)),
                ('job_role', models.CharField(max_length=100)),
                ('pain_level', models.IntegerField(help_text='Rate from 1 (minor annoyance) to 10 (critical issue)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('occasionally', 'Occasionally')], default='daily', max_length=20)),
                ('affected_people', models.CharField(choices=[('just_me', 'Just me'), ('my_team', 'My team (5-20)'), ('my_company', 'My company (20+)'), ('my_industry', 'My industry (hundreds+)')], default='just_me', max_length=20)),
                ('workaround', models.TextField(blank=True, null=True)),
                ('contact_info', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_contact', models.BooleanField(default=False)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=20)),
                ('is_solved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
