# Generated by Django 4.2.28 on 2026-02-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='slug-default', max_length=200, unique=True),
        ),
    ]
