# Generated by Django 4.2.28 on 2026-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
