# Generated by Django 4.2.28 on 2026-02-10 16:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_alter_problem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_level', models.IntegerField(help_text='Rate from 1 (minor annoyance) to 10 (critical issue)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('occasionally', 'Occasionally')], default='daily', max_length=20)),
                ('affected_people', models.CharField(choices=[('just_me', 'Just me'), ('my_team', 'My team (5-20)'), ('my_company', 'My company (20+)'), ('my_industry', 'My industry (hundreds+)')], default='just_me', max_length=20)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_author', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='problems.problem')),
            ],
        ),
    ]
