# Generated by Django 4.2.28 on 2026-02-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_take'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='take',
            options={'ordering': ['-created_date']},
        ),
    ]
