# Generated by Django 4.2.28 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_options_alter_take_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=20),
        ),
    ]
