# Generated by Django 4.2.28 on 2026-02-13 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_take_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
