# Generated by Django 4.2.28 on 2026-02-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pain_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Rate from 1 (minor annoyance) to 10 (critical issue)'),
        ),
        migrations.AlterField(
            model_name='take',
            name='pain_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, help_text='Rate from 1 (minor annoyance) to 10 (critical issue)'),
        ),
    ]
