# Generated by Django 4.2.28 on 2026-02-19 08:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
